spring.application.name=airBnbApp
#dbConfiguration
spring.datasource.url=jdbc:postgresql://localhost:5432/airBnb
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
server.servlet.context-path=/api/v1
spring.profiles.active=local
stripe.secret.key=dummy_key
stripe.webhook.secret=dummy_secret
jwt.secretKey=dummy_jwt_key